<a href="/users/new">Новый пользователь </a>
<style>
    table {
        table-layout: fixed; /* Фиксированная ширина ячеек */
        width: 50%; /* Ширина таблицы */
    }
</style>
<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<?php foreach ($users as $user): ?>
<table>
    <tr>
        <td>
            <?= htmlspecialchars($user->id) ?>
        </td>
        <td>
            <?= htmlspecialchars($user->name) ?>
        </td>
        <td>
            <?= htmlspecialchars($user->mail) ?>
        </td>
    </tr>
</table>
<?php endforeach ?>