<div><a href="/users/new">Новый пользователь </a></div>
<div><a href="/">main</a></div>
<style>
    table {
        table-layout: fixed; /* Фиксированная ширина ячеек */
        width: 50%; /* Ширина таблицы */
    }
</style>
<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<?php foreach ($users as $user): ?>
<table>
    <tr>
        <td>
            <?= htmlspecialchars($user->id) ?>
        </td>
        <td>
            <a href="/users/<?= htmlspecialchars($user->id) ?>"><?= htmlspecialchars($user->name) ?></a>

        </td>
        <td>
            <?= htmlspecialchars($user->mail) ?>
        </td>
    </tr>
</table>
<?php endforeach ?>

<!--Переключение между страницами -->
<div>
    <a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">пред</a> <a href="?page=<?= $page + 1 ?>">след</a>
</div>
