<a href="/users/new">Новый пользователь </a>
<style>
    table {
        table-layout: fixed; /* Фиксированная ширина ячеек */
        width: 50%; /* Ширина таблицы */
    }
</style>


<?php foreach ($users as $user): ?>
<table>
    <tr>
        <td>
            <?= htmlspecialchars($user->id) ?>
        </td>
        <td>
            <?= htmlspecialchars($user->name) ?>
        </td>
        <td>
            <?= htmlspecialchars($user->mail) ?>
        </td>
    </tr>
</table>
<?php endforeach ?>