<form action="/users" method="post">
    <div>
        <label>
            NickNAME -
            <input type="text" name="user[name]" value ="<?= htmlspecialchars($user['name']) ?>">
        </label>
    </div>
    <div>
        <label>
            @MAIL
            <input type="email" name="user[mail]" value ="<?= htmlspecialchars($user['mail']) ?>">
        </label>
    </div>
    <div>
        <label>
            #ID
            <input type="number" name="user[id]"  value ="<?= htmlspecialchars($user['id']) ?>" >
        </label>
    </div>
    <input type="submit" value="Create">
</form>